appr:
- name: quay.io/samsung_cnct/fluent-bit
  repository: appr://
  version: 0.0.0-8
- name: quay.io/samsung_cnct/elasticsearch-chart
  repository: appr://
  version: 0.0.0-28
- name: quay.io/samsung_cnct/curator
  repository: appr://
  version: 0.0.1-0
- name: quay.io/samsung_cnct/kibana-chart
  repository: appr://
  version: 0.0.0-4
- name: quay.io/samsung_cnct/eventrouter
  repository: appr://
  version: 0.0.1-36
